### ISSUE TITLE
Reporting section is empty? 

### ISSUE THREAD

**Issue by zarmehdi1** [lucianopuccio/golem#100]
reporting section is not showing anything why ?
![image](https://user-images.githubusercontent.com/24219160/38395634-4e03b538-394d-11e8-8fa4-c3cc3518dee6.png)

**Comment by r-roos** [comment]
I noticed the same thing when using internet explorer, is this also what you are using ?

**Comment by lucianopuccio** [comment]
At the moment only suites are listed in the gui reports, individual test reports still can be found in project/reports/single_tests as json files. In the future all test executions should be in the reports. Temporarily run the test from a suite.
