### ISSUE TITLE
How can we make the golem pick up the change in actions.py file

### ISSUE THREAD

**Issue by DowneyTung** [lucianopuccio/golem#102]
Hi there,
I am trying to build up some of my own self-defined actions in the actions.py file. But seems like the application is not picking up the change. Even if I made a change the existing method like from http_get to http_change, the UI is not picking up the change when I restart the server using 'golem gui'.
 Could you provide some instructions about how to add self-defined actions and make the UI pick up the change? 
Thank you very much!

**Comment by lucianopuccio** [comment]
Hi Downey, yes, if you want the code to be editable you would need to clone the repo locally and then run ```python setup.py develop``` or ```pip install . -e``` at the repo root. Alternatively you can add custom actions into a page object so it won´t be overwritten when you update Golem

Regards
