### ISSUE TITLE
Closing a tab

### ISSUE THREAD

**Issue by Averlath** [lucianopuccio/golem#103]
Hello, 
I'm pretty new at Golem and so far haven't been able to figure out how to close a window/tab without closing the whole browser? I couldn't find anything about that in the documentation, so I decided to ask here.

I'd appreciate any help! Thanks in advance!

**Comment by lucianopuccio** [comment]
Hey. So I'll be adding soon actions to deal with this and other stuff, see #106. But in the meantime you can still use Selenium. Suppose your test opens a new tab/window:

```python
from golem.browser import get_browser

browser = get_browser()
# switch to last window
browser.switch_to.window(browser.window_handles[-1])
browser.close()  # close the second tab/window
# switch back to original window
browser.switch_to.window(browser.window_handles[0])
```

It's cumbersome and needs improvement. I know.
