### ISSUE TITLE
Example for Basic Authentication

### ISSUE THREAD

**Issue by 42sol-eu** [lucianopuccio/golem#105]
Some Webservers use [Basic Authentication](https://de.wikipedia.org/wiki/HTTP-Authentifizierung) for login.

How would an implementation of a test script in golem for basic authentication look like?

**Comment by lucianopuccio** [comment]
So technically basic authentication is not standarized by webdriver yet. See https://github.com/w3c/webdriver/issues/385 and https://github.com/SeleniumHQ/selenium/issues/5471. Until this is implemented you have two options basically: hardcoding the credentials into the URL or using a third party tool like autohotkey or autoit.

To use the first option just navigate to 'http://username:password@rest-of-the-url'. As this is not guaranteed to work crossbrowser I don't think it should be implemented by Golem, but it can be easily achieved with some string formatting
