### ISSUE TITLE
GUI test parser cannot process relative imports

### ISSUE THREAD

**Issue by filiprichtarik** [lucianopuccio/golem#111]
version 0.5.0 
python 3.6.5

i prefer to edit test/page files in Pycharm with autocomplete feature 

once i edit test so the autocomplete can provide properties and functions, means adding
 
`from golem import actions`
`from ..pages import <list of pages>`

gui shows me that there are erors in the test code and it could not be parsed into the editor 
![screen shot 2018-06-28 at 14 45 26](https://user-images.githubusercontent.com/30689650/42034958-f2d0fb72-7ae1-11e8-8837-725872c5e826.png)

when i open the code, i can see this 
![screen shot 2018-06-28 at 14 49 34](https://user-images.githubusercontent.com/30689650/42035163-92024020-7ae2-11e8-8579-3f3c0ebe8600.png)

test can run, IMHO it's issue with parsing to the editor

**Comment by filiprichtarik** [comment]
sorry for the spam 
issue is actually a fix in p3.6

**Comment by NihadMemmedli** [comment]
It is also does not work on me. Give same error "ImportError: attempted relative import with no known parent package".
