### ISSUE TITLE
MacOS updating webdrivers fails on geckodriver

### ISSUE THREAD

**Issue by HoughIO** [lucianopuccio/golem#116]
When running `$ webdriver-manager update`, it tries to reach 
>https://github.com/mozilla/geckodriver/releases/download/v0.21/geckodriver-v0.21-macos.tar.gz

Which is the incorrect URL. It should point to

>https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-macos.tar.gz

Output:
```
(env) gorm:test Graham$ webdriver-manager update
INFO updating chromedriver
INFO got chromedriver_2.41
INFO updating geckodriver
ERROR there was a 404 error trying to reach https://github.com/mozilla/geckodriver/releases/download/v0.21/geckodriver-v0.21-macos.tar.gz
This probably means the requested version does not exist.
```

The URL is missing `.0` in the version number.

**Comment by r-roos** [comment]
Known issue: https://github.com/lucianopuccio/webdriver-manager/pull/1 is created by @filiprichtarik

**Comment by lucianopuccio** [comment]
This has been fixed.

Run ```pip install --upgrade py-webdriver-manager``` to get the latest version.
