### ISSUE TITLE
Import Conflicts ?

### ISSUE THREAD

**Issue by YiiKuoChong** [lucianopuccio/golem#24]
While reading the code I found a file called ```selenium.py``` at ``` golem/golem/selenium.py```
, won't that cause an import conflict?

**Comment by lucianopuccio** [comment]
It would cause conflict if you import selenium and golem.selenium which would not be needed. However, I agree it's confusing. I'll look into renaming it and documenting the public API. Thanks!

**Comment by lucianopuccio** [comment]
golem.selenium is renamed to golem.browser
The public API is documented here: http://golem-framework.readthedocs.io/en/latest/golem-api.html#golem-browser

Thanks for your input
