### ISSUE TITLE
When selecting an environment in a test case, the test case runs without waiting for the continue box to be clicked

### ISSUE THREAD

**Issue by danielmaddern** [lucianopuccio/golem#30]
Might be as designed, but if you select the wrong environment from the dropdown, you have no way to back out, dismiss button doesn't cancel the test(will raise as a separate issue)

**Comment by danielmaddern** [comment]
ignore dismiss button issue.

**Comment by lucianopuccio** [comment]
I agree, the event on change was removed + changed the button to 'Run', thanks
