### ISSUE TITLE
GUI: suggestions for test step arguments are displayed in incorrect order

### ISSUE THREAD

**Issue by r-roos** [lucianopuccio/golem#41]
With the current latest source of (22-10-2017) I am experiencing the following GUI bug.

The field indicators when adding a test step that requires multiple arguments is displayed in the incorrect order within the gui. This results in a issue where once calling the test step the function is called with the wrong order of arguments. 

Example:
The following test step function:
![image](https://user-images.githubusercontent.com/32699953/31864691-28e65fe8-b762-11e7-8307-4ff38266f315.png)

end up being presented as (TOP: correct order for function call, BOTTOM: incorrect initial suggestions, the bug)
![image](https://user-images.githubusercontent.com/32699953/31864699-4c1ffc58-b762-11e7-92c4-891abb4bcfb6.png)

The result of the above:
![image](https://user-images.githubusercontent.com/32699953/31864719-bc30879c-b762-11e7-894a-3aeb1f4f61ed.png)

**Comment by r-roos** [comment]
I am afraid the bug has not resolved in the latest 0.3.0 version on PyPi 

Example with 0.3.0
used page function:
![image](https://user-images.githubusercontent.com/32699953/32038323-91a2aad6-ba29-11e7-9e30-d258db8d417e.png)

When selecting the page function in test case, notice the initial suggest order b, c, a:
![image](https://user-images.githubusercontent.com/32699953/32038365-c685d930-ba29-11e7-9389-305306bffc07.png)

When filling in the values as suggested via the GUI the function/test step ends up being called as:
![image](https://user-images.githubusercontent.com/32699953/32038433-2416825c-ba2a-11e7-934a-818834ceb26e.png)

**Comment by lucianopuccio** [comment]
Hi R-roos I will re-test, which OS are you using?

**Comment by r-roos** [comment]
Thank you!

As requested. I am running Ubuntu 16.04.3 with the following Chrome version:

Google Chrome | 61.0.3163.91 (Official Build) unknown (64-bit)
-- | --
Revision | 2f544949507dc5330b714cb017e3f584e791a1bf-refs/branch-heads/3163@{#1194}
OS | Linux

**Comment by r-roos** [comment]
@lucianopuccio do you need any more help for recreating this issue ?

**Comment by lucianopuccio** [comment]
I could reproduce it and it should be fixed in 0.3.1, let me know if it's still happening. Thanks!

**Comment by r-roos** [comment]
@lucianopuccio 

Retested and working like a charm now! thanks a lot for fixing this one.
