### ISSUE TITLE
Unable to run any tests/suites after physically moving tests through windows explorer

### ISSUE THREAD

**Issue by vishal-agg** [lucianopuccio/golem#45]
Unable to run any tests/suites after physically moving tests through windows explorer from one suite to another or outside any folder ,directly inside test folder.
![golem_unabletoexecuteaftertestmovementfromwindowexplorer](https://user-images.githubusercontent.com/9512482/31865660-6ad1502e-b740-11e7-8fa1-c752a94cc736.png)

**Comment by lucianopuccio** [comment]
The error I see in the stack trace is that environments.json has incorrect syntax, json needs double quotes.
I added a friendlier error message.
It would be better if the gui validated json syntax when saving environments data
Sorry for the inconvenience
