### ISSUE TITLE
Not able to add steps after updating to 0.2.2

### ISSUE THREAD

**Issue by zeeshanyshaikh** [lucianopuccio/golem#53]
After updating to [0.2.2] - 2017-10-16, am not able to add steps.

Error : 

> (index):260 Uncaught ReferenceError: testCase is not defined at HTMLButtonElement.onclick

![add step error](https://user-images.githubusercontent.com/6223015/31892440-a5e61fd2-b826-11e7-930b-4d8cd9f01801.jpg)

**Comment by danielmaddern** [comment]
This is working correctly in newer versions. Tested in Chrome on 0.3.0 and 0.3.1. 
Update and retest? Also make sure you clear cache after updating.

**Comment by lucianopuccio** [comment]
This was probably due to cache. Reopen if it is still happening. Thanks!
