### ISSUE TITLE
Decimal test data being converted to floats

### ISSUE THREAD

**Issue by danielmaddern** [lucianopuccio/golem#57]
data file:
test_decimal
20.00
'20.00'
"20.00"

if any of the first 3 options are set in the data file, it gets converted to 20.0 when the test runs and can cause validation errors. Works correctly if I save the data in the gui as "20.00" which comes out as """20.00""" in the csv.

Working as intended? Running golem-framework-0.3.1

**Comment by lucianopuccio** [comment]
check #51, it's probably related

**Comment by danielmaddern** [comment]
Yep, same issue.. Happy to close this one and deal with it there.
