### ISSUE TITLE
Unable to recover from Syntax error in Page object Method

### ISSUE THREAD

**Issue by vishal-agg** [lucianopuccio/golem#59]
On having any python syntax error like missing parentheses in the page object method, unable to correct it.
Always getting "builtins.SyntaxError" page from multiple locations.Tried:
1).Directly from error page, could not find a way back to Original Page to correct the syntax error.
2).On opening browser again, and navigating to Page object code, still opening same error page.
3).Navigating from test to Page object code.

**Suggested Approach**: There should be a way to go back from error page to Page object code to correct it.
![golem_onhavingsyntaxerrorsatpageobjectfunction](https://user-images.githubusercontent.com/9512482/32546077-dc775e4a-c44b-11e7-9ed8-a142c9cfda51.PNG)

**Comment by lucianopuccio** [comment]
yep, this is valid issue, it should display the code anyway but with some warning of invalid syntax or highlighting problematic lines. Will look into it. thanks!

**Comment by lucianopuccio** [comment]
I applied a fix for this for both page builder and test builder, if you have any comments, please let me know. thanks!
