### ISSUE TITLE
How are you supposed to get the current URL?

### ISSUE THREAD

**Issue by mark0978** [lucianopuccio/golem#66]
There seems to be no equivalent to driver.getCurrentUrl()

**Comment by danielmaddern** [comment]
Try this..
from golem.browser import get_browser
wd = get_browser()
print(wd.current_url)

Sounds like it's something useful to have as a golem action tho.. Will add it in an send a pull request shortly, unless you want to do it @mark0978

**Comment by mark0978** [comment]
I'm working on it, but the infrastucture for adding things that are usable everywhere is "difficult"  I've had to create an empty Page object so I have some place to put it

**Comment by lucianopuccio** [comment]
I created a ticket to track more actions that should be added to the list of golem.actions here: #80

**Comment by lucianopuccio** [comment]
get_current_url() was added to golem.actions in 0.4.5
