### ISSUE TITLE
strings in test data are not correctly handled

### ISSUE THREAD

**Issue by r-roos** [lucianopuccio/golem#89]
I have been running into some issues using strings in test data in version 0.4.5

It seems strings are always parsed with single qoute's, the following example illustrates the issue:
The test:
```
description = 'Issue with using test data'

pages = []

data = [
    {
        'whattosearch': 'cars',
    },
    {
        'whattosearch': 'planes',
    },
]

def setup(data):
    pass

def test(data):
    navigate('https://www.google.com/')
    send_keys(('id', 'lst-ib'), data.whattosearch)


def teardown(data):
    pass

```

Search on google is 'cars' instead of cars:
<img width="570" alt="screen shot 2018-01-20 at 15 18 35" src="https://user-images.githubusercontent.com/32699953/35184812-acee693c-fdfa-11e7-9c18-0aa7c567524c.png">

Issue experienced on version 0.4.5:
# Software versions used
certifi==2018.1.18
chardet==3.0.4
click==6.7
Flask==0.12.2
Flask-Login==0.4.1
golem-framework==0.4.5
idna==2.6
itsdangerous==0.24
Jinja2==2.10
MarkupSafe==1.0
psycopg2==2.7.3.2
redis==2.10.6
requests==2.18.4
selenium==3.8.1
urllib3==1.22
Werkzeug==0.14.1

Python version 3.5.4 and 3.6.4

**Comment by lucianopuccio** [comment]
This has been fixed in 0.5.0. 

Just a small detail that double quote strings get converted to single quotes in the GUI but 'something "like" this' and "something 'like' this" will work as expected.
